# Generated by Django 2.0.7 on 2018-07-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='expanse',
            old_name='title',
            new_name='name',
        ),
    ]
