# Generated by Django 2.0.7 on 2018-07-24 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20180724_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budget.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='expanse',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expanse',
            name='project',
        ),
        migrations.DeleteModel(
            name='Expanse',
        ),
    ]
